apiVersion: v1
kind: Service
metadata:
  name: datadog-cluster-agent
  labels:
    app: datadog-cluster-agent
spec:
  ports:
  - port: 5005
    protocol: TCP
  selector:
    app: datadog-cluster-agent
