apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: datadog-cluster-agent
      name: datadog-agent
      annotations:
        ad.datadoghq.com/datadog-cluster-agent.check_names: '["prometheus"]'
        ad.datadoghq.com/datadog-cluster-agent.init_configs: '[{}]'
        ad.datadoghq.com/datadog-cluster-agent.instances: '[{"prometheus_url": "http://%%host%%:5000/metrics","namespace": "datadog.cluster_agent","metrics": ["go_goroutines","go_memstats_*","process_*","api_requests","datadog_requests","external_metrics", "cluster_checks_*"]}]'
    spec:
      serviceAccountName: datadog-cluster-agent
      containers:
      - image: datadog/cluster-agent:latest
        imagePullPolicy: Always
        name: datadog-cluster-agent
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-api-key
                key: token
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
          - name: DD_CLUSTER_CHECKS_ENABLED
            value: "true"
          - name: DD_LOG_LEVEL
            value: "debug"
          - name: DD_EXTRA_CONFIG_PROVIDERS
            value: "kube_services kube_endpoints"
          - name: DD_EXTRA_LISTENERS
            value: "kube_services kube_endpoints"
          - name: DD_CLUSTER_AGENT_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: datadog-auth-token
                key: token
        volumeMounts:
          - mountPath: /conf.d/kube_apiserver_metrics.yaml
            name: control-plane-yaml
            subPath: kube_apiserver_metrics.yaml
          - mountPath: /conf.d/kube_controller_manager.yaml
            name: control-plane-yaml
            subPath: kube_controller_manager.yaml
          - mountPath: /conf.d/kube_scheduler.yaml
            name: control-plane-yaml
            subPath: kube_scheduler.yaml
          - mountPath: /conf.d/etcd.yaml
            name: control-plane-yaml
            subPath: etcd.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: control-plane-yaml
          name: control-plane-yaml
