apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-crashloopbackoff
  labels:
    app: sample-crashloopbackoff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-crashloopbackoff
  template:
    metadata:
      labels:
        app: sample-crashloopbackoff
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/false"]
