apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web-v1
  namespace: default
  labels:
    app: hello-web-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-web-v1
  template:
    metadata:
      labels:
        app: hello-web-v1
    spec:
      containers:
        - name: web
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-web-v1
  namespace: default
spec:
  ports:
  - name: hello-web-v1
    port: 8080
    targetPort: 8080
  selector:
    pp: hello-web-v1
