apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
  namespace: default
  labels:
    app: hello-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-web
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
        - name: web
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-web
  namespace: default
spec:
  ports:
  - name: hello-web
    port: 8080
    targetPort: 8080
  selector:
    app: hello-web
