apiVersion: apps/v1
kind: Deployment
metadata:
  name: macchiato
  labels:
    app: macchiato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: macchiato
  template:
    metadata:
      labels:
        app: macchiato
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/false"]
