apiVersion: v1
kind: ConfigMap
metadata:
  name: control-plane-yaml
data:
  kube_apiserver_metrics.yaml: |
    cluster_check: true
    init_config:
    instances:
    - prometheus_url: localhost:443/metrics

  kube_audit.yaml: |
    logs:
    - type: file
      path: /var/log/kubernetes/apiserver/audit.log
      service: kube-apiserver-audit
      source: kubernetes
      tags: kube-apiserver:audit

  kube_controller_manager.yaml: |
    cluster_check: true
    init_config:
    instances:
    - prometheus_url: http://localhost:10252/metrics
      leader_election: true

  kube_scheduler.yaml: |
    cluster_check: true
    init_config:
    instances:
    - prometheus_url: http://localhost:10251/metrics
      leader_election: true       

  etcd.yaml: |
    cluster_check: true
    init_config:
    instances:
    - url: http://localhost:2379/metrics
      init_config:
